Repository GispoCoding/eis_toolkit, pull requests merged in 2023-11, with the labels that each got.

#215 Add possibility to create PDF from autogenerated documentation
  docs/stylesheets/extra.css
  instructions/generating_documentation.md
  mkdocs.yml
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: documentation, enhancement

#217 216 modify modules
  docs/data_tools/class_balancing.md
  docs/exploratory_analyses/descriptive_statistics.md
  docs/exploratory_analyses/feature_importance.md
  docs/exploratory_analyses/statistical_testing.md
  docs/spatial_analyses/cell_based_association.md
  docs/spatial_analyses/distance_computation.md
  docs/statistical_analyses/descriptive_statistics.md
  docs/statistical_analyses/statistical_testing.md
  docs/training_data_tools/class_balancing.md
  docs/transformations/binarize.md
  docs/transformations/clip.md
  docs/transformations/linear.md
  docs/transformations/logarithmic.md
  docs/transformations/sigmoid.md
  docs/transformations/winsorize.md
  docs/vector_processing/cell_based_association.md
  docs/vector_processing/distance_computation.md
  eis_toolkit/cli.py
  eis_toolkit/dummy_tests/__init__.py
  eis_toolkit/dummy_tests/dummy.py
  eis_toolkit/dummy_tests/dummy_gdal.py
  eis_toolkit/dummy_tests/dummy_sklearn.py
  eis_toolkit/exploratory_analyses/descriptive_statistics.py
  eis_toolkit/exploratory_analyses/pca.py
  eis_toolkit/exploratory_analyses/statistical_tests.py
  eis_toolkit/raster_processing/check_raster_grids.py
  eis_toolkit/raster_processing/clipping.py
  eis_toolkit/raster_processing/create_constant_raster.py
  eis_toolkit/raster_processing/snapping.py
  eis_toolkit/spatial_analyses/__init__.py
  eis_toolkit/statistical_analyses/__init__.py
  eis_toolkit/training_data_tools/__init__.py
  eis_toolkit/training_data_tools/class_balancing.py
  eis_toolkit/transformations/binarize.py
  eis_toolkit/transformations/clip.py
  eis_toolkit/transformations/linear.py
  eis_toolkit/transformations/logarithmic.py
  eis_toolkit/transformations/sigmoid.py
  eis_toolkit/transformations/winsorize.py
  eis_toolkit/utilities/checks/__init__.py
  eis_toolkit/utilities/checks/crs.py
  eis_toolkit/utilities/checks/dataframe.py
  eis_toolkit/utilities/checks/geometry.py
  eis_toolkit/utilities/checks/parameter.py
  eis_toolkit/utilities/checks/raster.py
  eis_toolkit/utilities/miscellaneous.py
  eis_toolkit/validation/calculate_base_metrics.py
  eis_toolkit/validation/plot_correlation_matrix.py
  eis_toolkit/vector_processing/cell_based_association.py
  eis_toolkit/vector_processing/distance_computation.py
  notebooks/cba_introduction.ipynb
  notebooks/csv_to_geopandas.ipynb
  notebooks/eis_toolkit_and_notebooks.ipynb
  tests/checks/check_raster_grids_test.py
  tests/exploratory_analyses/descriptive_statistics_test.py
  tests/exploratory_analyses/statistical_tests_test.py
  tests/training_data_tools/class_balancing_test.py
  tests/vector_processing/cell_based_association_test.py
  tests/vector_processing/test_distance_computation.py
Labels: modification

#240 Fix output dtype check for OHE
  tests/transformations/one_hot_encode_test.py
Labels: bug

#242 Force check_minimax_position to return bool
  eis_toolkit/utilities/checks/parameter.py
Labels: bug
