Repository GispoCoding/eis_toolkit, pull requests merged in 2023-08, with the labels that each got.

#175 Change extent into optional parameter
  eis_toolkit/vector_processing/kriging_interpolation.py
  tests/vector_processing/test_kriging_interpolation.py
Labels: modification

#171 Added unit conversions
  eis_toolkit/utilities/conversions.py
  tests/utilities/conversions_test.py
Labels: enhancement

#165 152 add parallel coordinates plot
  eis_toolkit/exceptions.py
  eis_toolkit/exploratory_analyses/parallel_coordinates.py
  notebooks/parallel_coordinates.ipynb
Labels: enhancement, EDA
